behaviors:
  TowerAgent:
    trainer_type: ppo
    hyperparameters:
      batch_size: 512
      buffer_size: 2048
      learning_rate: 0.003
      beta: 0.01
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 4
      learning_rate_schedule: linear
    network_settings:
      normalize: true
      hidden_units: 256
      num_layers: 3
      vis_encode_type: simple
      continuous_actions: 2
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.2       
    keep_checkpoints: 5
    max_steps: 150000      
    time_horizon: 2048
    summary_freq: 1000
